version: '3.8'
services:
    # bot
    sakura_mini_admin:
        # 指定容器运行的镜像,指向Dockerfile文件
        build: .
        # 自定义容器名称
        container_name: sakura_mini_admin
        # 将主机的数据卷或着文件挂载到容器里
        restart: always
        environment:
          TZ: Asia/Shanghai
        # 容器的端口xx映射到宿主机的端口xx
        ports:
            - "5555:5555"
        # 服务的日志记录配置
        logging:
            driver: "json-file"
            options:
                max-size: "100m" # 单个文件大小为200k
                max-file: "2" # 最多10个文件
